name: Docker Image CI

on:
  push:
    branches:
      - production-build

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-website:$(date +%s)
    - name: Deploy Docker Image to Heroku App
      uses: jctaveras/heroku-deploy@v1.1.0
      with:
        # Email linked to your Heroku account
        email: jessephilip@gmail.com
        # Your Heroku API Key
        api_key: a85107d8-d64c-41d2-9cb6-a2280af3ac99
        # Your Heroku App Name
        app_name: jessematherne
        # Dokerfile path
        dockerfile: Dockerfile
